"""Build ACORD retriever training/evaluation examples.

This script generates query-document examples with positive/easy/hard labels.
It is a *data-prep step* for LoRA training and does not run evaluation.
"""

from __future__ import annotations

from pathlib import Path

from src.b2_reranking.acord_retriever_dataset import write_acord_retriever_examples
from src.ontology.acord_near_miss_graph import DEFAULT_NEAR_MISS_PATH
from src.utils.__utils__ import processed_dataset_paths, raw_dataset_dir

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

RAW_DIR = raw_dataset_dir("ACORD")

# Thresholds (YOUR INTERVENTION: decide what counts as positive)
POS_THRESHOLD = 3
NEG_THRESHOLD = 1
HARD_THRESHOLD = 2

TRAIN_SPLIT = "train"
DEV_SPLIT = "dev"

MAX_POS = None
MAX_EASY_NEG = 100
MAX_HARD_NEG = 100
MAX_ONTOLOGY_NEG = 100
DROP_NO_POSITIVES = True

NEAR_MISS_PATH = DEFAULT_NEAR_MISS_PATH

DATASET_VERSION = "v1"
# Generated by `python -m orchestrators.d_evaluate.acord_trick_query_miner`.
TRICK_QUERIES_PATH = Path("data/results/acord_retriever/dev/assurance/trick_queries.jsonl")
INCLUDE_TRICK_QUERIES_TRAIN = True
INCLUDE_TRICK_QUERIES_DEV = False


def main() -> None:
    train_base = processed_dataset_paths("acord", TRAIN_SPLIT)["base"]
    dev_base = processed_dataset_paths("acord", DEV_SPLIT)["base"]
    train_out = train_base / "retriever_examples.jsonl"
    train_easy_out = train_base / "retriever_examples_easy.jsonl"
    train_hard_out = train_base / "retriever_examples_hard.jsonl"
    dev_out = dev_base / "retriever_examples.jsonl"

    train_summary = write_acord_retriever_examples(
        split=TRAIN_SPLIT,
        raw_dir=RAW_DIR,
        near_miss_path=NEAR_MISS_PATH,
        out_path=train_out,
        easy_out_path=train_easy_out,
        hard_out_path=train_hard_out,
        pos_threshold=POS_THRESHOLD,
        neg_threshold=NEG_THRESHOLD,
        hard_threshold=HARD_THRESHOLD,
        max_pos=MAX_POS,
        max_easy_neg=MAX_EASY_NEG,
        max_hard_neg=MAX_HARD_NEG,
        max_ontology_neg=MAX_ONTOLOGY_NEG,
        trick_queries_path=TRICK_QUERIES_PATH,
        include_trick_queries=INCLUDE_TRICK_QUERIES_TRAIN,
        dataset_version=DATASET_VERSION,
        drop_no_positives=DROP_NO_POSITIVES,
        include_near_miss=True,
        include_siblings=True,
        require_near_miss=True,
    )
    dev_summary = write_acord_retriever_examples(
        split=DEV_SPLIT,
        raw_dir=RAW_DIR,
        near_miss_path=NEAR_MISS_PATH,
        out_path=dev_out,
        pos_threshold=POS_THRESHOLD,
        neg_threshold=NEG_THRESHOLD,
        hard_threshold=HARD_THRESHOLD,
        max_pos=MAX_POS,
        max_easy_neg=MAX_EASY_NEG,
        max_hard_neg=MAX_HARD_NEG,
        max_ontology_neg=MAX_ONTOLOGY_NEG,
        trick_queries_path=TRICK_QUERIES_PATH,
        include_trick_queries=INCLUDE_TRICK_QUERIES_DEV,
        dataset_version=DATASET_VERSION,
        drop_no_positives=DROP_NO_POSITIVES,
        include_near_miss=True,
        include_siblings=True,
        require_near_miss=True,
    )

    print(f"[train examples] {train_summary}")
    print(f"[dev examples] {dev_summary}")


if __name__ == "__main__":
    main()
